# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-GP1BYDRqqOKjH_IknYhZ1cqUuKTOll
"""

from datetime import datetime, timedelta, timezone

# ==========================
# CONFIGURATION
# ==========================
SHOW_HOURS = True
SHOW_MINUTES = True
SHOW_SECONDS = True
SHOW_MILLISECONDS = True
SHOW_MICROSECONDS = True  # Smallest precision supported by datetime

UTC_MINUS_3 = timezone(timedelta(hours=-3))


def time_until(hour, minute):
    now = datetime.now(UTC_MINUS_3)

    today_target = now.replace(
        hour=hour,
        minute=minute,
        second=0,
        microsecond=0
    )

    if today_target <= now:
        today_target += timedelta(days=1)

    return today_target - now


def format_timedelta(td):
    total_seconds = int(td.total_seconds())

    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60

    microseconds = td.microseconds
    milliseconds = microseconds // 1000
    remaining_microseconds = microseconds % 1000

    parts = []

    if SHOW_HOURS:
        parts.append(f"{hours}h")
    if SHOW_MINUTES:
        parts.append(f"{minutes}m")
    if SHOW_SECONDS:
        parts.append(f"{seconds}s")
    if SHOW_MILLISECONDS:
        parts.append(f"{milliseconds}ms")
    if SHOW_MICROSECONDS:
        parts.append(f"{remaining_microseconds}µs")

    return " ".join(parts)


def main():
    times = {
        "café da manhã": time_until(9, 30),
        "almoço": time_until(12, 0),
        "café da tarde": time_until(15, 30)
    }

    closest_event = min(times, key=times.get)
    td = times[closest_event]

    formatted_time = format_timedelta(td)

    print(f"Faltam {formatted_time} para o {closest_event}!")


if __name__ == "__main__":
    main()

"""# Task
Provide the full Python script to calculate and display the time until the next meal in Portuguese.

## Definir Horários das Refeições e Fuso Horário

### Subtask:
Configurar os horários exatos das refeições (9:30, 12:00, 15:30) e o fuso horário correto (UTC-3) para garantir cálculos precisos.

## Calcular Tempo Restante

### Subtask:
Desenvolver ou adaptar a função Python para calcular o tempo que falta até cada uma das refeições especificadas, considerando o tempo atual.

### Revisão da Função `time_until`

1.  **Cálculo Correto do `timedelta`:**
    *   A função `time_until(hour, minute)` obtém o `datetime` atual (`now`) com o fuso horário `UTC_MINUS_3`.
    *   Ela cria um `datetime` para o alvo (`today_target`) usando o ano, mês e dia atuais, mas com as `hour` e `minute` fornecidas, e segundos/microssegundos zerados.
    *   A diferença (`today_target - now`) é um `timedelta`, indicando que a função calcula corretamente a diferença de tempo.

2.  **Tratamento de Tempo Alvo Passado:**
    *   A condição `if today_target <= now:` verifica se o tempo alvo para o dia atual já passou ou é o momento exato.
    *   Se for o caso, `today_target += timedelta(days=1)` adiciona um dia ao `today_target`, garantindo que o cálculo do `timedelta` seja sempre para o próximo evento futuro.
    *   Este mecanismo assegura que a função retorna o tempo até a próxima ocorrência do evento se a hora de hoje já tiver sido atingida.

3.  **Confirmação do Fuso Horário `UTC_MINUS_3`:**
    *   A linha `now = datetime.now(UTC_MINUS_3)` explicitamente define o objeto `now` para usar o fuso horário `UTC_MINUS_3`.
    *   O objeto `today_target` é criado a partir de `now` usando `now.replace(...)`, o que, por padrão, mantém as informações de fuso horário do objeto `now`. Portanto, `today_target` também estará no fuso horário `UTC_MINUS_3`.
    *   Isso confirma que a função realiza os cálculos consistentemente dentro do fuso horário especificado, garantindo precisão.

## Formatar Tempo em Português

### Subtask:
Implementar uma função para formatar o objeto de tempo restante (timedelta) em uma string legível em português, incluindo horas, minutos, segundos, milissegundos e microssegundos, conforme o exemplo.

### Revisão da função `format_timedelta`

A função `format_timedelta` está bem implementada e atende a todos os requisitos:

1.  **Extração e Formatação Correta**: A função extrai corretamente horas, minutos e segundos a partir do `total_seconds` do objeto `timedelta`. Milissegundos e microssegundos são extraídos diretamente do atributo `microseconds`.
2.  **Unidades e Junção**: As unidades ('h', 'm', 's', 'ms', 'µs') são adicionadas a cada parte do tempo e a string final é unida por espaços, conforme o exemplo.
3.  **Uso de Flags Booleanas**: As variáveis de configuração `SHOW_HOURS`, `SHOW_MINUTES`, `SHOW_SECONDS`, `SHOW_MILLISECONDS` e `SHOW_MICROSECONDS` são utilizadas corretamente para controlar quais componentes do tempo são incluídos na string formatada, garantindo flexibilidade na apresentação.

## Identificar Próxima Refeição

### Subtask:
Determinar qual das refeições (café da manhã, almoço, café da tarde) é a próxima a acontecer, com base no horário atual.

```markdown
### Identificação da Próxima Refeição

No código fornecido, a função `main` é responsável por determinar qual das refeições definidas (`café da manhã`, `almoço`, `café da tarde`) é a próxima a acontecer.

1.  **Cálculo do tempo até cada refeição:**
    Dentro de `main`, um dicionário chamado `times` é criado. Para cada refeição, a função `time_until(hour, minute)` é chamada. Esta função calcula a diferença de tempo (`timedelta`) entre o horário atual (ajustado para UTC-3) e o horário da refeição. Se o horário da refeição já passou hoje, ela calcula para o dia seguinte.

    ```python
    times = {
        "café da manhã": time_until(9, 30),
        "almoço": time_until(12, 0),
        "café da tarde": time_until(15, 30)
    }
    ```

2.  **Identificação do evento mais próximo:**
    Após popular o dicionário `times` com os `timedelta` para cada refeição, a linha `closest_event = min(times, key=times.get)` é utilizada.

    *   `min()` é uma função Python que retorna o menor item de uma sequência.
    *   O argumento `key=times.get` especifica que a comparação para encontrar o "menor" item deve ser baseada nos *valores* do dicionário (`timedelta`), e não nas chaves. O valor `timedelta` mais curto (o menor tempo restante) corresponde à refeição mais próxima.

    Portanto, esta lógica **corretamente** identifica a próxima refeição a ocorrer, encontrando o `timedelta` mínimo entre as opções e retornando a chave (nome da refeição) associada a esse `timedelta`.

3.  **Formatação e Impressão:**
    Finalmente, o `timedelta` do evento mais próximo é formatado usando `format_timedelta` e a mensagem final é impressa, indicando quanto tempo falta para a próxima refeição.

O resultado da execução deste código demonstra que ele identifica corretamente o próximo evento e o tempo restante até ele.

## Gerar Saída Final

### Subtask:
Compor a mensagem final em português, informando o tempo restante para a próxima refeição, no formato 'Faltam Xh Ym Zs Ams Bµs para o [Nome da Refeição]!'

## Finalizar Tarefa

### Subtask:
Fornecer o script Python completo com toda a lógica implementada para calcular e exibir o tempo até a próxima refeição em português, pronto para ser integrado em um projeto web maior.

## Summary:

### Data Analysis Key Findings

*   **Timezone and Meal Times Configuration**: The script accurately configures the `UTC-3` timezone and defines meal times (9:30 for 'café da manhã', 12:00 for 'almoço', and 15:30 for 'café da tarde'), using `datetime.now(UTC_MINUS_3)` for consistent timezone application.
*   **Time Remaining Calculation**: The `time_until` function correctly calculates the time difference (`timedelta`) until each meal. It handles cases where a meal has already passed for the current day by projecting the calculation to the next day, ensuring that the function always returns the time to the next future occurrence.
*   **Localized Time Formatting**: The `format_timedelta` function effectively converts `timedelta` objects into a readable Portuguese string, precisely extracting and displaying hours, minutes, seconds, milliseconds, and microseconds. It uses configurable boolean flags to control the level of detail shown in the output.
*   **Next Meal Identification**: The script accurately identifies the next upcoming meal by comparing the calculated `timedelta` for all defined meals and selecting the one with the shortest remaining time.
*   **Final Output Generation**: The final message is correctly composed in Portuguese, adhering to the specified format: "Faltam {formatted\_time} para o {closest\_event}!", incorporating the precisely formatted time and the name of the next meal.

### Insights or Next Steps

*   The provided Python script is fully functional and meets all specified requirements for calculating and displaying the time until the next meal in Portuguese.
*   For future enhancements, consider externalizing meal times configuration (e.g., via a configuration file or database) to allow for easier modification without code changes, or implementing functionality to add or remove meal times dynamically.
"""